"""Initial migration

Revision ID: 16ac566932d6
Revises: 9012edc8c72d
Create Date: 2025-12-19 16:27:11.906055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16ac566932d6'
down_revision: Union[str, None] = '9012edc8c72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('actor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_tenant_idempotency')
    )
    op.create_index(op.f('ix_events_tenant_id'), 'events', ['tenant_id'], unique=False)
    op.create_table('event_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('entity_kind', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_entities_kind_id', 'event_entities', ['entity_kind', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_entities_kind_id', table_name='event_entities')
    op.drop_table('event_entities')
    op.drop_index(op.f('ix_events_tenant_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###

