"""Align schema with requirements

Revision ID: 76b493660380
Revises: 16ac566932d6
Create Date: 2025-12-19 16:39:36.318607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76b493660380'
down_revision: Union[str, None] = '16ac566932d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE event_entities, events CASCADE")
    op.add_column('event_entities', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('event_entities', sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_event_entities_kind_id'), table_name='event_entities')
    op.create_index('ix_event_entities_query_accel', 'event_entities', ['tenant_id', 'entity_kind', 'entity_id', sa.literal_column('occurred_at DESC'), sa.literal_column('event_id DESC')], unique=False)
    op.add_column('events', sa.Column('actor_kind', sa.String(), nullable=False))
    op.add_column('events', sa.Column('actor_id', sa.String(), nullable=False))
    op.add_column('events', sa.Column('hash', sa.String(), nullable=False))
    op.drop_index(op.f('ix_events_tenant_id'), table_name='events')
    op.create_index('ix_events_tenant_occurred_event', 'events', ['tenant_id', sa.literal_column('occurred_at DESC'), sa.literal_column('event_id DESC')], unique=False)
    op.create_index('ix_events_tenant_type_occurred', 'events', ['tenant_id', 'type', sa.literal_column('occurred_at DESC')], unique=False)
    op.drop_column('events', 'actor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('actor', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index('ix_events_tenant_type_occurred', table_name='events')
    op.drop_index('ix_events_tenant_occurred_event', table_name='events')
    op.create_index(op.f('ix_events_tenant_id'), 'events', ['tenant_id'], unique=False)
    op.drop_column('events', 'hash')
    op.drop_column('events', 'actor_id')
    op.drop_column('events', 'actor_kind')
    op.drop_index('ix_event_entities_query_accel', table_name='event_entities')
    op.create_index(op.f('ix_event_entities_kind_id'), 'event_entities', ['entity_kind', 'entity_id'], unique=False)
    op.drop_column('event_entities', 'occurred_at')
    op.drop_column('event_entities', 'tenant_id')
    # ### end Alembic commands ###

